dist: trusty
sudo: required
language: node_js
node_js:
  - "6.9.5"
os:
  - linux

install:
  - npm install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "46d1d6da-8ea5-4ac2-98ad-a09b39295587"
  app:
    master: weather-service-dev